"""add server status

Revision ID: 53dd795dd762
Revises: fafca7755f49
Create Date: 2026-03-11 19:52:23.486981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53dd795dd762'
down_revision: Union[str, None] = 'fafca7755f49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('status', sa.Enum('RUNNING', 'EXPIRED', 'STOPPED', 'FAILED', 'WAITING', name='task_status'), nullable=False))
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('RUNNING', 'EXPIRED', 'STOPPED', 'FAILED', name='task_status'),
               type_=sa.Enum('RUNNING', 'STOPPED', name='server_status'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('RUNNING', 'STOPPED', name='server_status'),
               type_=postgresql.ENUM('RUNNING', 'EXPIRED', 'STOPPED', 'FAILED', name='task_status'),
               existing_nullable=False)
    op.drop_column('servers', 'status')
    # ### end Alembic commands ###
