"""add server status

Revision ID: 53dd795dd762
Revises: fafca7755f49
Create Date: 2026-03-11 19:52:23.486981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53dd795dd762'
down_revision: Union[str, None] = 'fafca7755f49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    server_status = sa.Enum('RUNNING', 'STOPPED', name='server_status')
    server_status.create(op.get_bind(), checkfirst=True)
    # Add status column to servers table
    op.add_column(
        'servers',
        sa.Column('status', server_status, nullable=False, server_default='RUNNING'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'status')
    server_status = sa.Enum('RUNNING', 'STOPPED', name='server_status')
    server_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###