"""init

Revision ID: fafca7755f49
Revises: 
Create Date: 2026-03-07 02:48:32.314513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fafca7755f49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('cpu_total', sa.Integer(), nullable=False),
    sa.Column('ram_total', sa.Integer(), nullable=False),
    sa.Column('gpu_total', sa.Integer(), nullable=False),
    sa.Column('cpu_free', sa.Integer(), nullable=False),
    sa.Column('ram_free', sa.Integer(), nullable=False),
    sa.Column('gpu_free', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=False),
    sa.CheckConstraint('cpu_free >= 0 AND cpu_free <= cpu_total', name='ck_server_cpu_free'),
    sa.CheckConstraint('cpu_total >= 0', name='ck_server_cpu_total_nonneg'),
    sa.CheckConstraint('gpu_free >= 0 AND gpu_free <= gpu_total', name='ck_server_gpu_free'),
    sa.CheckConstraint('gpu_total >= 0', name='ck_server_gpu_total_nonneg'),
    sa.CheckConstraint('ram_free >= 0 AND ram_free <= ram_total', name='ck_server_ram_free'),
    sa.CheckConstraint('ram_total >= 0', name='ck_server_ram_total_nonneg'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('tasks',
    sa.Column('cpu_req', sa.Integer(), nullable=False),
    sa.Column('ram_req', sa.Integer(), nullable=False),
    sa.Column('gpu_req', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'EXPIRED', 'STOPPED', 'FAILED', 'WAITING', name='task_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_uid', sa.String(length=50), nullable=True),
    sa.Column('uid', sa.String(length=50), nullable=False),
    sa.CheckConstraint('cpu_req >= 0', name='ck_task_cpu_req_nonneg'),
    sa.CheckConstraint('gpu_req >= 0', name='ck_task_gpu_req_nonneg'),
    sa.CheckConstraint('ram_req >= 0', name='ck_task_ram_req_nonneg'),
    sa.ForeignKeyConstraint(['server_uid'], ['servers.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_tasks_status_expires_at', 'tasks', ['status', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_status_expires_at', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('servers')
    # ### end Alembic commands ###
